import { KnowledgeArticle } from "../types/knowledge";

export const knowledgeItems: KnowledgeArticle[] = [
  {
    id: "1",
    title: "Cách Chọn Chất Liệu Bảng Hiệu Phù Hợp Với Môi Trường",
    description:
      "Hướng dẫn chi tiết về việc lựa chọn vật liệu bảng hiệu dựa trên điều kiện môi trường và thời tiết.",
    content: "Nội dung chi tiết về cách chọn chất liệu bảng hiệu...",
    image: "/images/banghieu.jpg",
    date: "2024-01-15",
    category: "Vật liệu",
    slug: "cach-chon-chat-lieu-bang-hieu-phu-hop-voi-moi-truong",
    author: "Nguyễn Văn A",
    readTime: "5 phút",
    tags: ["vật liệu", "môi trường", "bảng hiệu"],
  },
  {
    id: "2",
    title: "Kỹ Thuật Lắp Đặt Bảng Hiệu LED An Toàn",
    description:
      "Hướng dẫn chi tiết về quy trình và kỹ thuật lắp đặt bảng hiệu LED đảm bảo an toàn và hiệu quả.",
    content: "Nội dung chi tiết về kỹ thuật lắp đặt bảng hiệu LED...",
    image: "/images/bienquangcao.jpg",
    date: "2024-01-10",
    category: "Kỹ thuật",
    slug: "ky-thuat-lap-dat-bang-hieu-led-an-toan",
    author: "Trần Văn B",
    readTime: "8 phút",
    tags: ["LED", "lắp đặt", "an toàn"],
  },
  {
    id: "3",
    title: "Bảo Trì Bảng Hiệu Định Kỳ - Những Điều Cần Biết",
    description:
      "Tổng hợp kiến thức về quy trình bảo trì, bảo dưỡng bảng hiệu để kéo dài tuổi thọ sản phẩm.",
    content: "Nội dung chi tiết về bảo trì bảng hiệu...",
    image: "/images/hopden.jpg",
    date: "2024-01-05",
    category: "Bảo trì",
    slug: "bao-tri-bang-hieu-dinh-ky",
    author: "Lê Thị C",
    readTime: "6 phút",
    tags: ["bảo trì", "bảo dưỡng", "định kỳ"],
  },
  {
    id: "4",
    title: "Nguyên Lý Hoạt Động Của Đèn LED Ma Trận",
    description:
      "Giải thích chi tiết về cơ chế hoạt động và ứng dụng của công nghệ LED ma trận trong bảng hiệu.",
    content: "Nội dung chi tiết về đèn LED ma trận...",
    image: "/images/bienquangcao.jpg",
    date: "2024-01-01",
    category: "Công nghệ",
    slug: "nguyen-ly-hoat-dong-cua-den-led-ma-tran",
    author: "Phạm Văn D",
    readTime: "10 phút",
    tags: ["LED", "ma trận", "công nghệ"],
  },
  {
    id: "5",
    title: "Quy Định Pháp Lý Về Quảng Cáo Ngoài Trời",
    description:
      "Cập nhật các quy định mới nhất về quảng cáo ngoài trời và những điều cần lưu ý khi làm bảng hiệu.",
    content: "Nội dung chi tiết về quy định pháp lý...",
    image: "/images/banghieu.jpg",
    date: "2023-12-28",
    category: "Pháp lý",
    slug: "quy-dinh-phap-ly-ve-quang-cao-ngoai-troi",
    author: "Hoàng Văn E",
    readTime: "7 phút",
    tags: ["pháp lý", "quy định", "quảng cáo"],
  },
  {
    id: "6",
    title: "Thiết Kế Bảng Hiệu Theo Phong Thủy",
    description:
      "Hướng dẫn cách áp dụng nguyên tắc phong thủy trong thiết kế bảng hiệu cho doanh nghiệp.",
    content: "Nội dung chi tiết về phong thủy trong thiết kế bảng hiệu...",
    image: "/images/banghieu.jpg",
    date: "2023-12-25",
    category: "Thiết kế",
    slug: "thiet-ke-bang-hieu-theo-phong-thuy",
    author: "Nguyễn Thị F",
    readTime: "9 phút",
    tags: ["phong thủy", "thiết kế", "doanh nghiệp"],
  },
  {
    id: "7",
    title: "Công Nghệ LED Full Color Trong Bảng Hiệu",
    description:
      "Tìm hiểu về công nghệ LED full color và cách ứng dụng hiệu quả trong thiết kế bảng hiệu hiện đại.",
    content: "Nội dung chi tiết về công nghệ LED full color...",
    image: "/images/bienquangcao.jpg",
    date: "2023-12-20",
    category: "Công nghệ",
    slug: "cong-nghe-led-full-color-trong-bang-hieu",
    author: "Trần Văn G",
    readTime: "7 phút",
    tags: ["LED", "full color", "công nghệ"],
  },
  {
    id: "8",
    title: "Cách Tính Toán Kích Thước Bảng Hiệu Chuẩn",
    description:
      "Hướng dẫn cách tính toán kích thước bảng hiệu phù hợp với không gian và yêu cầu thẩm mỹ.",
    content: "Nội dung chi tiết về cách tính kích thước bảng hiệu...",
    image: "/images/banghieu.jpg",
    date: "2023-12-15",
    category: "Thiết kế",
    slug: "cach-tinh-toan-kich-thuoc-bang-hieu-chuan",
    author: "Nguyễn Thị H",
    readTime: "6 phút",
    tags: ["kích thước", "thiết kế", "tiêu chuẩn"],
  },
  {
    id: "9",
    title: "Xử Lý Sự Cố Thường Gặp Với Bảng Hiệu LED",
    description:
      "Hướng dẫn cách xử lý các sự cố phổ biến khi sử dụng bảng hiệu LED và cách khắc phục.",
    content: "Nội dung chi tiết về xử lý sự cố...",
    image: "/images/bienquangcao.jpg",
    date: "2023-12-10",
    category: "Bảo trì",
    slug: "xu-ly-su-co-thuong-gap-voi-bang-hieu-led",
    author: "Lê Văn I",
    readTime: "8 phút",
    tags: ["sự cố", "LED", "bảo trì"],
  },
  {
    id: "10",
    title: "Chọn Font Chữ Cho Bảng Hiệu Quảng Cáo",
    description:
      "Hướng dẫn cách chọn font chữ phù hợp để tăng tính thẩm mỹ và khả năng đọc cho bảng hiệu.",
    content: "Nội dung chi tiết về chọn font chữ...",
    image: "/images/chunoi.jpg",
    date: "2023-12-05",
    category: "Thiết kế",
    slug: "chon-font-chu-cho-bang-hieu-quang-cao",
    author: "Phạm Thị K",
    readTime: "5 phút",
    tags: ["font chữ", "thiết kế", "typography"],
  },
  {
    id: "11",
    title: "Ứng Dụng IoT Trong Bảng Hiệu Thông Minh",
    description:
      "Khám phá cách Internet of Things (IoT) đang cách mạng hóa ngành công nghiệp bảng hiệu.",
    content: "Nội dung chi tiết về ứng dụng IoT...",
    image: "/images/bienquangcao.jpg",
    date: "2023-12-01",
    category: "Công nghệ",
    slug: "ung-dung-iot-trong-bang-hieu-thong-minh",
    author: "Hoàng Văn L",
    readTime: "10 phút",
    tags: ["IoT", "công nghệ", "thông minh"],
  },
  {
    id: "12",
    title: "Tiêu Chuẩn An Toàn Trong Lắp Đặt Bảng Hiệu",
    description:
      "Tổng hợp các tiêu chuẩn an toàn cần tuân thủ khi lắp đặt bảng hiệu quảng cáo.",
    content: "Nội dung chi tiết về tiêu chuẩn an toàn...",
    image: "/images/banghieu.jpg",
    date: "2023-11-28",
    category: "An toàn",
    slug: "tieu-chuan-an-toan-trong-lap-dat-bang-hieu",
    author: "Nguyễn Văn M",
    readTime: "9 phút",
    tags: ["an toàn", "lắp đặt", "tiêu chuẩn"],
  },
  {
    id: "13",
    title: "Sử Dụng Năng Lượng Mặt Trời Cho Bảng Hiệu",
    description:
      "Hướng dẫn tích hợp năng lượng mặt trời vào hệ thống bảng hiệu để tiết kiệm chi phí.",
    content: "Nội dung chi tiết về năng lượng mặt trời...",
    image: "/images/bienquangcao.jpg",
    date: "2023-11-25",
    category: "Công nghệ",
    slug: "su-dung-nang-luong-mat-troi-cho-bang-hieu",
    author: "Trần Thị N",
    readTime: "7 phút",
    tags: ["năng lượng mặt trời", "tiết kiệm", "xanh"],
  },
  {
    id: "14",
    title: "Kỹ Thuật Tạo Hiệu Ứng 3D Cho Bảng Hiệu",
    description:
      "Hướng dẫn các kỹ thuật tạo hiệu ứng 3D ấn tượng cho bảng hiệu quảng cáo.",
    content: "Nội dung chi tiết về hiệu ứng 3D...",
    image: "/images/chunoi.jpg",
    date: "2023-11-20",
    category: "Kỹ thuật",
    slug: "ky-thuat-tao-hieu-ung-3d-cho-bang-hieu",
    author: "Lê Văn O",
    readTime: "8 phút",
    tags: ["3D", "hiệu ứng", "kỹ thuật"],
  },
  {
    id: "15",
    title: "Chống Chọi Với Thời Tiết Khắc Nghiệt",
    description:
      "Các giải pháp bảo vệ bảng hiệu trong điều kiện thời tiết khắc nghiệt như mưa bão.",
    content: "Nội dung chi tiết về chống chọi thời tiết...",
    image: "/images/banghieu.jpg",
    date: "2023-11-15",
    category: "Bảo trì",
    slug: "chong-choi-voi-thoi-tiet-khac-nghiet",
    author: "Phạm Văn P",
    readTime: "6 phút",
    tags: ["thời tiết", "bảo vệ", "bảo trì"],
  },
  {
    id: "16",
    title: "Tối Ưu Hóa Chi Phí Vận Hành Bảng Hiệu",
    description:
      "Hướng dẫn cách tiết kiệm chi phí vận hành và bảo trì bảng hiệu hiệu quả.",
    content: "Nội dung chi tiết về tối ưu chi phí...",
    image: "/images/bienquangcao.jpg",
    date: "2023-11-10",
    category: "Kinh tế",
    slug: "toi-uu-hoa-chi-phi-van-hanh-bang-hieu",
    author: "Hoàng Thị Q",
    readTime: "7 phút",
    tags: ["chi phí", "tối ưu", "tiết kiệm"],
  },
  {
    id: "17",
    title: "Xu Hướng Thiết Kế Bảng Hiệu 2024",
    description:
      "Cập nhật những xu hướng thiết kế bảng hiệu mới nhất trong năm 2024.",
    content: "Nội dung chi tiết về xu hướng thiết kế...",
    image: "/images/banghieu.jpg",
    date: "2023-11-05",
    category: "Xu hướng",
    slug: "xu-huong-thiet-ke-bang-hieu-2024",
    author: "Nguyễn Văn R",
    readTime: "8 phút",
    tags: ["xu hướng", "thiết kế", "2024"],
  },
  {
    id: "18",
    title: "Tích Hợp Đèn LED RGB Trong Bảng Hiệu",
    description:
      "Hướng dẫn cách tích hợp và điều khiển đèn LED RGB trong bảng hiệu quảng cáo.",
    content: "Nội dung chi tiết về LED RGB...",
    image: "/images/bienquangcao.jpg",
    date: "2023-11-01",
    category: "Công nghệ",
    slug: "tich-hop-den-led-rgb-trong-bang-hieu",
    author: "Trần Văn S",
    readTime: "9 phút",
    tags: ["LED", "RGB", "điều khiển"],
  },
  {
    id: "19",
    title: "Bảo Vệ Bảng Hiệu Khỏi Tia UV",
    description:
      "Các phương pháp và vật liệu giúp bảo vệ bảng hiệu khỏi tác động của tia UV.",
    content: "Nội dung chi tiết về bảo vệ UV...",
    image: "/images/banghieu.jpg",
    date: "2023-10-28",
    category: "Bảo trì",
    slug: "bao-ve-bang-hieu-khoi-tia-uv",
    author: "Lê Thị T",
    readTime: "6 phút",
    tags: ["UV", "bảo vệ", "vật liệu"],
  },
  {
    id: "20",
    title: "Quy Trình Sản Xuất Chữ Nổi Inox",
    description:
      "Tìm hiểu quy trình sản xuất chữ nổi inox từ thiết kế đến hoàn thiện.",
    content: "Nội dung chi tiết về sản xuất chữ nổi...",
    image: "/images/chunoi.jpg",
    date: "2023-10-25",
    category: "Sản xuất",
    slug: "quy-trinh-san-xuat-chu-noi-inox",
    author: "Phạm Văn U",
    readTime: "10 phút",
    tags: ["inox", "chữ nổi", "sản xuất"],
  },
  {
    id: "21",
    title: "Ứng Dụng AI Trong Thiết Kế Bảng Hiệu",
    description:
      "Khám phá cách trí tuệ nhân tạo đang thay đổi ngành thiết kế bảng hiệu.",
    content: "Nội dung chi tiết về ứng dụng AI...",
    image: "/images/bienquangcao.jpg",
    date: "2023-10-20",
    category: "Công nghệ",
    slug: "ung-dung-ai-trong-thiet-ke-bang-hieu",
    author: "Hoàng Văn V",
    readTime: "8 phút",
    tags: ["AI", "thiết kế", "công nghệ"],
  },
  {
    id: "22",
    title: "Lựa Chọn Vị Trí Đặt Bảng Hiệu Hiệu Quả",
    description:
      "Hướng dẫn cách chọn vị trí đặt bảng hiệu để tối ưu hiệu quả quảng cáo.",
    content: "Nội dung chi tiết về chọn vị trí...",
    image: "/images/banghieu.jpg",
    date: "2023-10-15",
    category: "Marketing",
    slug: "lua-chon-vi-tri-dat-bang-hieu-hieu-qua",
    author: "Nguyễn Thị X",
    readTime: "7 phút",
    tags: ["vị trí", "marketing", "quảng cáo"],
  },
  {
    id: "23",
    title: "Kỹ Thuật Hàn Trong Sản Xuất Bảng Hiệu",
    description:
      "Tìm hiểu các kỹ thuật hàn chuyên dụng trong sản xuất bảng hiệu kim loại.",
    content: "Nội dung chi tiết về kỹ thuật hàn...",
    image: "/images/banghieu.jpg",
    date: "2023-10-10",
    category: "Kỹ thuật",
    slug: "ky-thuat-han-trong-san-xuat-bang-hieu",
    author: "Trần Văn Y",
    readTime: "9 phút",
    tags: ["hàn", "kỹ thuật", "kim loại"],
  },
  {
    id: "24",
    title: "Thiết Kế Bảng Hiệu Cho Thương Hiệu Cao Cấp",
    description:
      "Các nguyên tắc và kỹ thuật thiết kế bảng hiệu cho các thương hiệu cao cấp.",
    content: "Nội dung chi tiết về thiết kế cao cấp...",
    image: "/images/banghieu.jpg",
    date: "2023-10-05",
    category: "Thiết kế",
    slug: "thiet-ke-bang-hieu-cho-thuong-hieu-cao-cap",
    author: "Lê Văn Z",
    readTime: "8 phút",
    tags: ["cao cấp", "thiết kế", "thương hiệu"],
  },
  {
    id: "25",
    title: "Sử Dụng Vật Liệu Tái Chế Trong Bảng Hiệu",
    description:
      "Hướng dẫn cách sử dụng và tận dụng vật liệu tái chế trong sản xuất bảng hiệu.",
    content: "Nội dung chi tiết về vật liệu tái chế...",
    image: "/images/banghieu.jpg",
    date: "2023-10-01",
    category: "Vật liệu",
    slug: "su-dung-vat-lieu-tai-che-trong-bang-hieu",
    author: "Phạm Thị AA",
    readTime: "6 phút",
    tags: ["tái chế", "vật liệu", "môi trường"],
  },
  {
    id: "26",
    title: "Tối Ưu Hóa Ánh Sáng Cho Bảng Hiệu Ban Đêm",
    description:
      "Hướng dẫn cách tối ưu hóa hiệu quả chiếu sáng cho bảng hiệu vào ban đêm.",
    content: "Nội dung chi tiết về tối ưu ánh sáng...",
    image: "/images/bienquangcao.jpg",
    date: "2023-09-28",
    category: "Kỹ thuật",
    slug: "toi-uu-hoa-anh-sang-cho-bang-hieu-ban-dem",
    author: "Hoàng Văn BB",
    readTime: "7 phút",
    tags: ["ánh sáng", "ban đêm", "tối ưu"],
  },
  {
    id: "27",
    title: "Thiết Kế Bảng Hiệu Cho Ngành Y Tế",
    description:
      "Hướng dẫn thiết kế bảng hiệu chuyên nghiệp cho các cơ sở y tế và phòng khám.",
    content: "Nội dung chi tiết về thiết kế y tế...",
    image: "/images/banghieu.jpg",
    date: "2023-09-25",
    category: "Thiết kế",
    slug: "thiet-ke-bang-hieu-cho-nganh-y-te",
    author: "Nguyễn Văn CC",
    readTime: "8 phút",
    tags: ["y tế", "thiết kế", "chuyên ngành"],
  },
  {
    id: "28",
    title: "Bảo Trì Hệ Thống Điện Trong Bảng Hiệu",
    description:
      "Hướng dẫn quy trình bảo trì và kiểm tra hệ thống điện trong bảng hiệu.",
    content: "Nội dung chi tiết về bảo trì điện...",
    image: "/images/bienquangcao.jpg",
    date: "2023-09-20",
    category: "Bảo trì",
    slug: "bao-tri-he-thong-dien-trong-bang-hieu",
    author: "Trần Thị DD",
    readTime: "9 phút",
    tags: ["điện", "bảo trì", "an toàn"],
  },
  {
    id: "29",
    title: "Thiết Kế Bảng Hiệu Cho Nhà Hàng",
    description:
      "Các nguyên tắc và ý tưởng thiết kế bảng hiệu độc đáo cho nhà hàng.",
    content: "Nội dung chi tiết về thiết kế nhà hàng...",
    image: "/images/banghieu.jpg",
    date: "2023-09-15",
    category: "Thiết kế",
    slug: "thiet-ke-bang-hieu-cho-nha-hang",
    author: "Lê Văn EE",
    readTime: "7 phút",
    tags: ["nhà hàng", "thiết kế", "ẩm thực"],
  },
  {
    id: "30",
    title: "Ứng Dụng AR Trong Bảng Hiệu Tương Tác",
    description:
      "Khám phá cách augmented reality (AR) đang thay đổi cách tương tác với bảng hiệu.",
    content: "Nội dung chi tiết về ứng dụng AR...",
    image: "/images/bienquangcao.jpg",
    date: "2023-09-10",
    category: "Công nghệ",
    slug: "ung-dung-ar-trong-bang-hieu-tuong-tac",
    author: "Phạm Văn FF",
    readTime: "10 phút",
    tags: ["AR", "tương tác", "công nghệ"],
  },
  {
    id: "31",
    title: "Chọn Màu Sắc Cho Bảng Hiệu Theo Tâm Lý",
    description:
      "Phân tích tác động tâm lý của màu sắc và cách áp dụng trong thiết kế bảng hiệu.",
    content: "Nội dung chi tiết về tâm lý màu sắc...",
    image: "/images/banghieu.jpg",
    date: "2023-09-05",
    category: "Thiết kế",
    slug: "chon-mau-sac-cho-bang-hieu-theo-tam-ly",
    author: "Hoàng Thị GG",
    readTime: "8 phút",
    tags: ["màu sắc", "tâm lý", "thiết kế"],
  },
  {
    id: "32",
    title: "Kỹ Thuật In UV Trên Bảng Hiệu",
    description:
      "Tìm hiểu về công nghệ in UV và ứng dụng trong sản xuất bảng hiệu.",
    content: "Nội dung chi tiết về in UV...",
    image: "/images/bienquangcao.jpg",
    date: "2023-09-01",
    category: "Kỹ thuật",
    slug: "ky-thuat-in-uv-tren-bang-hieu",
    author: "Nguyễn Văn HH",
    readTime: "7 phút",
    tags: ["in UV", "kỹ thuật", "công nghệ"],
  },
  {
    id: "33",
    title: "Thiết Kế Bảng Hiệu Cho Trường Học",
    description: "Hướng dẫn thiết kế bảng hiệu phù hợp cho các cơ sở giáo dục.",
    content: "Nội dung chi tiết về thiết kế trường học...",
    image: "/images/banghieu.jpg",
    date: "2023-08-28",
    category: "Thiết kế",
    slug: "thiet-ke-bang-hieu-cho-truong-hoc",
    author: "Trần Văn II",
    readTime: "6 phút",
    tags: ["trường học", "giáo dục", "thiết kế"],
  },
  {
    id: "34",
    title: "Bảo Vệ Bảng Hiệu Khỏi Vandal",
    description:
      "Các giải pháp bảo vệ bảng hiệu khỏi hành vi phá hoại và vandal.",
    content: "Nội dung chi tiết về bảo vệ vandal...",
    image: "/images/banghieu.jpg",
    date: "2023-08-25",
    category: "An toàn",
    slug: "bao-ve-bang-hieu-khoi-vandal",
    author: "Lê Thị JJ",
    readTime: "7 phút",
    tags: ["bảo vệ", "an toàn", "vandal"],
  },
  {
    id: "35",
    title: "Thiết Kế Bảng Hiệu Cho Spa",
    description:
      "Hướng dẫn thiết kế bảng hiệu sang trọng và tinh tế cho spa và thẩm mỹ viện.",
    content: "Nội dung chi tiết về thiết kế spa...",
    image: "/images/banghieu.jpg",
    date: "2023-08-20",
    category: "Thiết kế",
    slug: "thiet-ke-bang-hieu-cho-spa",
    author: "Phạm Thị KK",
    readTime: "8 phút",
    tags: ["spa", "thẩm mỹ", "thiết kế"],
  },
  {
    id: "36",
    title: "Sử Dụng Đèn Neon Trong Bảng Hiệu",
    description:
      "Hướng dẫn sử dụng và bảo trì đèn neon trong thiết kế bảng hiệu.",
    content: "Nội dung chi tiết về đèn neon...",
    image: "/images/bienquangcao.jpg",
    date: "2023-08-15",
    category: "Kỹ thuật",
    slug: "su-dung-den-neon-trong-bang-hieu",
    author: "Hoàng Văn LL",
    readTime: "7 phút",
    tags: ["neon", "đèn", "thiết kế"],
  },
  {
    id: "37",
    title: "Quy Định Về Kích Thước Bảng Hiệu",
    description:
      "Tổng hợp các quy định pháp lý về kích thước bảng hiệu quảng cáo.",
    content: "Nội dung chi tiết về quy định kích thước...",
    image: "/images/banghieu.jpg",
    date: "2023-08-10",
    category: "Pháp lý",
    slug: "quy-dinh-ve-kich-thuoc-bang-hieu",
    author: "Nguyễn Văn MM",
    readTime: "6 phút",
    tags: ["pháp lý", "kích thước", "quy định"],
  },
  {
    id: "38",
    title: "Thiết Kế Bảng Hiệu Cho Showroom",
    description:
      "Hướng dẫn thiết kế bảng hiệu chuyên nghiệp cho showroom và cửa hàng trưng bày.",
    content: "Nội dung chi tiết về thiết kế showroom...",
    image: "/images/banghieu.jpg",
    date: "2023-08-05",
    category: "Thiết kế",
    slug: "thiet-ke-bang-hieu-cho-showroom",
    author: "Trần Thị NN",
    readTime: "8 phút",
    tags: ["showroom", "thiết kế", "trưng bày"],
  },
  {
    id: "39",
    title: "Bảo Trì Bảng Hiệu Mùa Mưa",
    description: "Hướng dẫn bảo trì và bảo dưỡng bảng hiệu trong mùa mưa.",
    content: "Nội dung chi tiết về bảo trì mùa mưa...",
    image: "/images/banghieu.jpg",
    date: "2023-08-01",
    category: "Bảo trì",
    slug: "bao-tri-bang-hieu-mua-mua",
    author: "Lê Văn OO",
    readTime: "7 phút",
    tags: ["bảo trì", "mùa mưa", "bảo dưỡng"],
  },
  {
    id: "40",
    title: "Thiết Kế Bảng Hiệu Cho Văn Phòng",
    description:
      "Hướng dẫn thiết kế bảng hiệu chuyên nghiệp cho văn phòng và công ty.",
    content: "Nội dung chi tiết về thiết kế văn phòng...",
    image: "/images/banghieu.jpg",
    date: "2023-07-28",
    category: "Thiết kế",
    slug: "thiet-ke-bang-hieu-cho-van-phong",
    author: "Phạm Văn PP",
    readTime: "6 phút",
    tags: ["văn phòng", "công ty", "thiết kế"],
  },
];
